<?php

/**
 * @file
 * Contains AFE SMS Gateway un/installtion hooks.
 */

/**
 * Implements hook_install().
 */
function sms_afe_install() {
  drupal_set_message(st('AFE SMS Gateway has been installed. Please set your settings in <a href="!link">configuration page</a>.',
    array('!link' => url('admin/smsframework/gateways/afe'))
  ));
}

/**
 * Implements hook_uninstall().
 */
function sms_afe_uninstall() {
  variable_del('sms_afe_settings');
}
